# TheThinkle.ai Configuration Example
# Copy this file to interests.yaml and customize for your needs

# Core interests - topics you want to stay updated on
interests:
  - artificial intelligence
  - machine learning
  - software engineering
  - cloud computing
  - cybersecurity

# Brief user background used to tailor scoring, tone, and relevance
user_profile: "A software engineer interested in staying current with technology and world events."

# Newsletter preferences
newsletter:
  tone: "witty"              # Options: professional, witty, casual, academic
  include_opinions: true     # Include AI-generated opinions and hot takes
  frequency: "weekly"        # Options: daily, weekly
  max_stories: 10           # Maximum number of stories per newsletter
  
# Content preferences
content:
  include_academic: true     # Include ArXiv papers
  include_reddit: true       # Include Reddit discussions
  include_youtube: true      # Include YouTube content summaries
  include_news: true         # Include news articles
  
  # Reddit-specific settings
  reddit:
    min_upvotes: 100        # Minimum upvotes for consideration
    max_age_hours: 48       # Only consider posts from last 48 hours
    
  # YouTube-specific settings
  youtube:
    min_views: 10000        # Minimum views for consideration
    max_duration_minutes: 60 # Skip videos longer than 60 minutes
    
# Output preferences
output:
  format: "markdown"         # Primary format: markdown, pdf, html
  include_sources: true      # Include source links
  include_summary_stats: true # Include reading time, word count, etc.

# Model configuration
# Available models: gpt-4, gpt-4-turbo, gpt-5, gpt-5-mini
models:
  planner: "gpt-5"           # Strategic planning agent
  scout: "gpt-5-mini"        # Information gathering (runs in parallel)
  evaluator: "gpt-5"         # Content evaluation and ranking
  writer: "gpt-5"            # Newsletter composition

# Maximum number of parallel research tasks
max_tasks: 3
